apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - image: vaultwarden/server:latest
          name: vaultwarden
          env:
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: admin
                  key: token
            - name: DOMAIN
              value: "https://vw.your.domain"
            - name: SMTP_HOST
              value: "mail.your.domain"
            - name: SMTP_FROM
              value: "vw@yourmail"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SSL
              value: "true"
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: password
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-data
      restartPolicy: Always
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-data

